#!/bin/bash

if [ -z "$1" ] || ! [[ "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "You need to supply a semver (syntax: $0 1.2.3)"
  exit 1
fi

set -e
git diff --exit-code
rm -rf node_modules
npm install
npm test
git diff --exit-code
json -I -f "package.json" -e "this.version=\"$1\""
git add package.json
git commit -m "v$1"
git push
git tag "v$1"
git push --tags
npm publish
